/*default configuration */
char inpath[125] = "test";
char config_file[125] = "config";
char method[56] = "accur";
bool isFm = true;
bool needOrig = false;
int usDisk = 0;
double initValue = 1.0;
int tsm_type = 1;
int kronsim_type=1;
int effisim_type=1;
bool hasIndex = false;
bool buildIndex = false;
bool queryInFile = false;
int numIter = 10; // default
double decayFactor = 0.6; // default
int sampleNum = 100;
int sampleQueryNum = 20;
int Rank = 20;
int psr_type = 0; 
int DEFAULT_TOPK = 50;
double DEFAULT_RANGE = 0.03;
int verticesNum = 456;
int edgeNum = 71959;
